[deps]
ADCME = "07b341a0-ce75-57c6-b2de-414ffdc00be5"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DuckDB = "d2f5444f-75bc-4fdf-ac35-56f514c445e1"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Parquet = "626c502c-15b0-58ad-a749-f091afb673ae"
Parquet2 = "98572fba-bba0-415d-956f-fa77e587d26d"
Pipe = "b98c9c47-44ae-5843-9183-064241ee97a0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
